"""aws connection

Revision ID: 0d25863d243f
Revises: b028e19a48d0
Create Date: 2026-09-13 20:20:24.085652

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0d25863d243f'
down_revision: Union[str, None] = 'b028e19a48d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aws_connections',
    sa.Column('account_id', sa.String(length=20), nullable=True),
    sa.Column('auth_mode', sa.Enum('LOCAL_PROFILE', 'ASSUME_ROLE', name='connection_auth_mode'), nullable=False),
    sa.Column('profile_name', sa.String(length=255), nullable=True),
    sa.Column('role_arn', sa.String(length=2048), nullable=True),
    sa.Column('region', sa.String(length=32), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'CONNECTED', 'DEGRADED', 'ERROR', name='connection_status'), nullable=False),
    sa.Column('read_only', sa.Boolean(), nullable=False),
    sa.Column('permission_status', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('last_cost_sync', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_resource_sync', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_event_sync', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_metrics_sync', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'account_id', name='uq_aws_connection_tenant_account')
    )
    op.create_index(op.f('ix_aws_connections_account_id'), 'aws_connections', ['account_id'], unique=False)
    op.create_index(op.f('ix_aws_connections_tenant_id'), 'aws_connections', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_aws_connections_tenant_id'), table_name='aws_connections')
    op.drop_index(op.f('ix_aws_connections_account_id'), table_name='aws_connections')
    op.drop_table('aws_connections')
    # ### end Alembic commands ###
