"""resource

Revision ID: 425c28340ff0
Revises: 7eeb8ff0345e
Create Date: 2026-09-13 21:01:18.495542

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '425c28340ff0'
down_revision: Union[str, None] = '7eeb8ff0345e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resources',
    sa.Column('account_id', sa.String(length=20), nullable=True),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('provider_resource_id', sa.String(length=512), nullable=False),
    sa.Column('arn', sa.String(length=2048), nullable=True),
    sa.Column('service', sa.String(length=64), nullable=False),
    sa.Column('resource_type', sa.String(length=64), nullable=False),
    sa.Column('region', sa.String(length=64), nullable=True),
    sa.Column('state', sa.String(length=64), nullable=True),
    sa.Column('provider_created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tags', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('resource_metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=True),
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.Column('environment', sa.String(length=64), nullable=True),
    sa.Column('attribution_status', sa.String(length=32), nullable=True),
    sa.Column('attribution_confidence', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'provider_resource_id', name='uq_resource_account_provider_id')
    )
    op.create_index(op.f('ix_resources_account_id'), 'resources', ['account_id'], unique=False)
    op.create_index(op.f('ix_resources_provider_resource_id'), 'resources', ['provider_resource_id'], unique=False)
    op.create_index(op.f('ix_resources_region'), 'resources', ['region'], unique=False)
    op.create_index(op.f('ix_resources_service'), 'resources', ['service'], unique=False)
    op.create_index(op.f('ix_resources_tenant_id'), 'resources', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_resources_tenant_id'), table_name='resources')
    op.drop_index(op.f('ix_resources_service'), table_name='resources')
    op.drop_index(op.f('ix_resources_region'), table_name='resources')
    op.drop_index(op.f('ix_resources_provider_resource_id'), table_name='resources')
    op.drop_index(op.f('ix_resources_account_id'), table_name='resources')
    op.drop_table('resources')
    # ### end Alembic commands ###
