"""aws connection external id

Revision ID: 43fc35d90707
Revises: a6575d93cf78
Create Date: 2026-09-14 14:55:08.579532

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43fc35d90707'
down_revision: Union[str, None] = 'a6575d93cf78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('aws_connections', sa.Column('external_id', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('aws_connections', 'external_id')
    # ### end Alembic commands ###
