"""anomaly and cost change

Revision ID: 81b223fdbc62
Revises: a02f417da66f
Create Date: 2026-09-13 21:28:46.662255

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '81b223fdbc62'
down_revision: Union[str, None] = 'a02f417da66f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anomalies',
    sa.Column('service', sa.String(length=255), nullable=True),
    sa.Column('detected_for', sa.Date(), nullable=False),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='anomaly_severity'), nullable=False),
    sa.Column('baseline', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('observed', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('difference', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('algorithm', sa.String(length=64), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'ACKNOWLEDGED', 'DISMISSED', name='anomaly_status'), nullable=False),
    sa.Column('evidence', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1', name='ck_anomaly_confidence'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'service', 'detected_for', 'algorithm', name='uq_anomaly_dedupe')
    )
    op.create_index(op.f('ix_anomalies_detected_for'), 'anomalies', ['detected_for'], unique=False)
    op.create_index(op.f('ix_anomalies_service'), 'anomalies', ['service'], unique=False)
    op.create_index(op.f('ix_anomalies_tenant_id'), 'anomalies', ['tenant_id'], unique=False)
    op.create_table('cost_changes',
    sa.Column('period_date', sa.Date(), nullable=False),
    sa.Column('service', sa.String(length=255), nullable=True),
    sa.Column('baseline_cost', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('observed_cost', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('absolute_change', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('percentage_change', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('classification', sa.Enum('GROWTH', 'ENGINEERING_CHANGE', 'WASTE', 'SUSPICIOUS', 'UNKNOWN', name='change_classification'), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('evidence', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cost_changes_period_date'), 'cost_changes', ['period_date'], unique=False)
    op.create_index(op.f('ix_cost_changes_service'), 'cost_changes', ['service'], unique=False)
    op.create_index(op.f('ix_cost_changes_tenant_id'), 'cost_changes', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cost_changes_tenant_id'), table_name='cost_changes')
    op.drop_index(op.f('ix_cost_changes_service'), table_name='cost_changes')
    op.drop_index(op.f('ix_cost_changes_period_date'), table_name='cost_changes')
    op.drop_table('cost_changes')
    op.drop_index(op.f('ix_anomalies_tenant_id'), table_name='anomalies')
    op.drop_index(op.f('ix_anomalies_service'), table_name='anomalies')
    op.drop_index(op.f('ix_anomalies_detected_for'), table_name='anomalies')
    op.drop_table('anomalies')
    # ### end Alembic commands ###
