"""attribution project identity event

Revision ID: a02f417da66f
Revises: 425c28340ff0
Create Date: 2026-09-13 21:11:16.773443

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a02f417da66f'
down_revision: Union[str, None] = '425c28340ff0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attributions',
    sa.Column('resource_id', sa.String(length=36), nullable=False),
    sa.Column('owner_user_id', sa.String(length=36), nullable=True),
    sa.Column('owner_label', sa.String(length=255), nullable=True),
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.Column('environment', sa.String(length=64), nullable=True),
    sa.Column('status', sa.Enum('ATTRIBUTED', 'SHARED', 'UNKNOWN', 'DISPUTED', name='attribution_status'), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=True),
    sa.Column('evidence', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_manual', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1', name='ck_attribution_confidence_range'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attributions_resource_id'), 'attributions', ['resource_id'], unique=False)
    op.create_index(op.f('ix_attributions_tenant_id'), 'attributions', ['tenant_id'], unique=False)
    op.create_table('aws_identities',
    sa.Column('account_id', sa.String(length=20), nullable=True),
    sa.Column('principal_type', sa.String(length=64), nullable=True),
    sa.Column('principal_id', sa.String(length=512), nullable=False),
    sa.Column('arn', sa.String(length=2048), nullable=True),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('identity_metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'account_id', 'principal_id', name='uq_aws_identity')
    )
    op.create_index(op.f('ix_aws_identities_account_id'), 'aws_identities', ['account_id'], unique=False)
    op.create_index(op.f('ix_aws_identities_principal_id'), 'aws_identities', ['principal_id'], unique=False)
    op.create_index(op.f('ix_aws_identities_tenant_id'), 'aws_identities', ['tenant_id'], unique=False)
    op.create_table('events',
    sa.Column('account_id', sa.String(length=20), nullable=True),
    sa.Column('provider_event_id', sa.String(length=255), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('event_name', sa.String(length=128), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('actor_principal_id', sa.String(length=512), nullable=True),
    sa.Column('actor_arn', sa.String(length=2048), nullable=True),
    sa.Column('resource_provider_id', sa.String(length=512), nullable=True),
    sa.Column('region', sa.String(length=64), nullable=True),
    sa.Column('normalized_data', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'provider_event_id', name='uq_event_provider_id')
    )
    op.create_index(op.f('ix_events_account_id'), 'events', ['account_id'], unique=False)
    op.create_index(op.f('ix_events_actor_principal_id'), 'events', ['actor_principal_id'], unique=False)
    op.create_index(op.f('ix_events_event_type'), 'events', ['event_type'], unique=False)
    op.create_index(op.f('ix_events_provider_event_id'), 'events', ['provider_event_id'], unique=False)
    op.create_index(op.f('ix_events_resource_provider_id'), 'events', ['resource_provider_id'], unique=False)
    op.create_index(op.f('ix_events_tenant_id'), 'events', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_events_timestamp'), 'events', ['timestamp'], unique=False)
    op.create_table('projects',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('budget', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_tenant_id'), 'projects', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_projects_tenant_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_events_timestamp'), table_name='events')
    op.drop_index(op.f('ix_events_tenant_id'), table_name='events')
    op.drop_index(op.f('ix_events_resource_provider_id'), table_name='events')
    op.drop_index(op.f('ix_events_provider_event_id'), table_name='events')
    op.drop_index(op.f('ix_events_event_type'), table_name='events')
    op.drop_index(op.f('ix_events_actor_principal_id'), table_name='events')
    op.drop_index(op.f('ix_events_account_id'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_aws_identities_tenant_id'), table_name='aws_identities')
    op.drop_index(op.f('ix_aws_identities_principal_id'), table_name='aws_identities')
    op.drop_index(op.f('ix_aws_identities_account_id'), table_name='aws_identities')
    op.drop_table('aws_identities')
    op.drop_index(op.f('ix_attributions_tenant_id'), table_name='attributions')
    op.drop_index(op.f('ix_attributions_resource_id'), table_name='attributions')
    op.drop_table('attributions')
    # ### end Alembic commands ###
