"""cost guardrail fields

Revision ID: a6575d93cf78
Revises: f84358d0c4b3
Create Date: 2026-09-14 14:09:35.093063

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6575d93cf78'
down_revision: Union[str, None] = 'f84358d0c4b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cost_estimates', sa.Column('guardrail_status', sa.String(length=32), nullable=True))
    op.add_column('cost_estimates', sa.Column('guardrail_warning_threshold', sa.Numeric(precision=18, scale=4), nullable=True))
    op.add_column('cost_estimates', sa.Column('guardrail_review_threshold', sa.Numeric(precision=18, scale=4), nullable=True))
    op.add_column('cost_estimates', sa.Column('guardrail_evaluated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('projects', sa.Column('guardrail_warning_threshold', sa.Numeric(precision=18, scale=4), nullable=True))
    op.add_column('projects', sa.Column('guardrail_review_threshold', sa.Numeric(precision=18, scale=4), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'guardrail_review_threshold')
    op.drop_column('projects', 'guardrail_warning_threshold')
    op.drop_column('cost_estimates', 'guardrail_evaluated_at')
    op.drop_column('cost_estimates', 'guardrail_review_threshold')
    op.drop_column('cost_estimates', 'guardrail_warning_threshold')
    op.drop_column('cost_estimates', 'guardrail_status')
    # ### end Alembic commands ###
