"""cost estimate deployment link

Revision ID: ad98d086f87b
Revises: b54f14bf4cd4
Create Date: 2026-09-13 21:51:38.691025

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad98d086f87b'
down_revision: Union[str, None] = 'b54f14bf4cd4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cost_estimates', sa.Column('account_id', sa.String(length=20), nullable=True))
    op.add_column('cost_estimates', sa.Column('project_id', sa.String(length=36), nullable=True))
    op.add_column('cost_estimates', sa.Column('environment', sa.String(length=64), nullable=True))
    op.add_column('cost_estimates', sa.Column('deployed_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_cost_estimates_account_id'), 'cost_estimates', ['account_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cost_estimates_account_id'), table_name='cost_estimates')
    op.drop_column('cost_estimates', 'deployed_at')
    op.drop_column('cost_estimates', 'environment')
    op.drop_column('cost_estimates', 'project_id')
    op.drop_column('cost_estimates', 'account_id')
    # ### end Alembic commands ###
