"""github and cost estimate

Revision ID: b54f14bf4cd4
Revises: 81b223fdbc62
Create Date: 2026-09-13 21:40:32.729876

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b54f14bf4cd4'
down_revision: Union[str, None] = '81b223fdbc62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cost_estimates',
    sa.Column('repository_id', sa.String(length=36), nullable=True),
    sa.Column('pr_number', sa.Integer(), nullable=True),
    sa.Column('base_commit', sa.String(length=64), nullable=True),
    sa.Column('head_commit', sa.String(length=64), nullable=True),
    sa.Column('baseline_monthly', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('proposed_monthly', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('estimated_monthly_delta', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('line_items', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('unsupported', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('iac_format', sa.String(length=32), nullable=False),
    sa.Column('pricing_source', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cost_estimates_repository_id'), 'cost_estimates', ['repository_id'], unique=False)
    op.create_index(op.f('ix_cost_estimates_tenant_id'), 'cost_estimates', ['tenant_id'], unique=False)
    op.create_table('github_pull_requests',
    sa.Column('repository_id', sa.String(length=36), nullable=False),
    sa.Column('pr_number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.Column('base_commit', sa.String(length=64), nullable=True),
    sa.Column('head_commit', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'repository_id', 'pr_number', name='uq_github_pr')
    )
    op.create_index(op.f('ix_github_pull_requests_repository_id'), 'github_pull_requests', ['repository_id'], unique=False)
    op.create_index(op.f('ix_github_pull_requests_tenant_id'), 'github_pull_requests', ['tenant_id'], unique=False)
    op.create_table('github_repositories',
    sa.Column('full_name', sa.String(length=512), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.Column('environment', sa.String(length=64), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'full_name', name='uq_github_repo_fullname')
    )
    op.create_index(op.f('ix_github_repositories_full_name'), 'github_repositories', ['full_name'], unique=False)
    op.create_index(op.f('ix_github_repositories_tenant_id'), 'github_repositories', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_github_repositories_tenant_id'), table_name='github_repositories')
    op.drop_index(op.f('ix_github_repositories_full_name'), table_name='github_repositories')
    op.drop_table('github_repositories')
    op.drop_index(op.f('ix_github_pull_requests_tenant_id'), table_name='github_pull_requests')
    op.drop_index(op.f('ix_github_pull_requests_repository_id'), table_name='github_pull_requests')
    op.drop_table('github_pull_requests')
    op.drop_index(op.f('ix_cost_estimates_tenant_id'), table_name='cost_estimates')
    op.drop_index(op.f('ix_cost_estimates_repository_id'), table_name='cost_estimates')
    op.drop_table('cost_estimates')
    # ### end Alembic commands ###
