"""cost record

Revision ID: babdd53f5f24
Revises: 0d25863d243f
Create Date: 2026-09-13 20:29:51.718870

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'babdd53f5f24'
down_revision: Union[str, None] = '0d25863d243f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cost_records',
    sa.Column('account_id', sa.String(length=20), nullable=True),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('service', sa.String(length=255), nullable=True),
    sa.Column('region', sa.String(length=64), nullable=True),
    sa.Column('resource_id', sa.String(length=512), nullable=True),
    sa.Column('resource_arn', sa.String(length=2048), nullable=True),
    sa.Column('usage_type', sa.String(length=255), nullable=True),
    sa.Column('operation', sa.String(length=255), nullable=True),
    sa.Column('cost', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('source_ref', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('natural_key', sa.String(length=64), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('cost >= 0', name='ck_cost_record_non_negative'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'natural_key', name='uq_cost_record_tenant_naturalkey')
    )
    op.create_index(op.f('ix_cost_records_account_id'), 'cost_records', ['account_id'], unique=False)
    op.create_index(op.f('ix_cost_records_natural_key'), 'cost_records', ['natural_key'], unique=False)
    op.create_index(op.f('ix_cost_records_period_start'), 'cost_records', ['period_start'], unique=False)
    op.create_index(op.f('ix_cost_records_resource_id'), 'cost_records', ['resource_id'], unique=False)
    op.create_index(op.f('ix_cost_records_service'), 'cost_records', ['service'], unique=False)
    op.create_index(op.f('ix_cost_records_source'), 'cost_records', ['source'], unique=False)
    op.create_index(op.f('ix_cost_records_tenant_id'), 'cost_records', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cost_records_tenant_id'), table_name='cost_records')
    op.drop_index(op.f('ix_cost_records_source'), table_name='cost_records')
    op.drop_index(op.f('ix_cost_records_service'), table_name='cost_records')
    op.drop_index(op.f('ix_cost_records_resource_id'), table_name='cost_records')
    op.drop_index(op.f('ix_cost_records_period_start'), table_name='cost_records')
    op.drop_index(op.f('ix_cost_records_natural_key'), table_name='cost_records')
    op.drop_index(op.f('ix_cost_records_account_id'), table_name='cost_records')
    op.drop_table('cost_records')
    # ### end Alembic commands ###
