"""action request and audit log

Revision ID: f84358d0c4b3
Revises: ad98d086f87b
Create Date: 2026-09-13 22:04:47.066069

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f84358d0c4b3'
down_revision: Union[str, None] = 'ad98d086f87b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('action_requests',
    sa.Column('action_type', sa.Enum('STOP_INSTANCE', name='action_type'), nullable=False),
    sa.Column('resource_id', sa.String(length=36), nullable=True),
    sa.Column('provider_resource_id', sa.String(length=512), nullable=True),
    sa.Column('account_id', sa.String(length=20), nullable=True),
    sa.Column('region', sa.String(length=64), nullable=True),
    sa.Column('requested_by', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'BLOCKED', 'FAILED', 'EXECUTED', name='action_status'), nullable=False),
    sa.Column('policy_result', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('result', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_action_requests_resource_id'), 'action_requests', ['resource_id'], unique=False)
    op.create_index(op.f('ix_action_requests_tenant_id'), 'action_requests', ['tenant_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('actor_user_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('resource_id', sa.String(length=512), nullable=True),
    sa.Column('aws_api', sa.String(length=128), nullable=True),
    sa.Column('request_summary', sa.String(length=1024), nullable=True),
    sa.Column('result', sa.String(length=32), nullable=False),
    sa.Column('detail', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor_user_id'), 'audit_logs', ['actor_user_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource_id'), 'audit_logs', ['resource_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_tenant_id'), 'audit_logs', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_logs_tenant_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_resource_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_action_requests_tenant_id'), table_name='action_requests')
    op.drop_index(op.f('ix_action_requests_resource_id'), table_name='action_requests')
    op.drop_table('action_requests')
    # ### end Alembic commands ###
